version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - ./uploads:/uploads
      - ./db:/prisma
    environment:
      PORT: 2998

