version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # You can change the port on host machine
      # Default port is 2998 on host machine
      - "2998:2998"
    volumes:
      # You can create and use another folder for uploads
      # Default folder is /uploads in current directory on host machine
      - ./uploads:/uploads
